apiVersion: v1
kind: PersistentVolume
metadata:
  name: e-commerce-database-volume
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /mnt/e-commerce-app-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e-commerce-database-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod